#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))

usage() {
    echo "
Usage: $(basename $0) [OPTIONS] [BRANCH]
Clear tip (or wip) in the remote

OPTIONS
    -a             clear all tips and wips
    -h             display this help message

All the unknown options are passed directly to the git-push command.
" 1>&2;
    exit 1;
}

. $SCRIPT_DIR/uri_parser.sh
. $SCRIPT_DIR/tip_config.sh

OPT_ALL=0
pushargs=""
args=
for arg in "$@"; do
    case "$arg" in
        -a) OPT_ALL=1
            ;;
        -h) usage
            ;;
        # unknown options go to arguments to git-push
        -*) pushargs="$pushargs $arg"
            ;;
        *) args="$args $arg"
            ;;
    esac
done
IFS=' ' read -a args <<< "$args"

branchargs=""

BRANCH="*"
if [ $OPT_ALL -eq 0 ]; then
   TIP=${args[0]:-HEAD}
   BRANCH=$(basename $(git rev-parse --abbrev-ref --symbolic $TIP))
   if [ -z "$BRANCH" ]; then
       die "No branch matches '$TIP'"
   fi
fi

branchprefix=${branchprefix/tip/[tw]ip}
branchargs=$(git branch -r --list "$remote/$branchprefix/$BRANCH" | sed "s#$remote/#:#")

[ -z "$branchargs" ] && exit 0

git push $pushargs $remote $branchargs
