#!/bin/bash

set -e

usage() {
    echo "
Usage: $(basename $0) [OPTIONS] <PR>
Fetch a pull-request from github

OPTIONS
    -b <branch>    Branch on which to checkout this pr
    -r <remote>    Use <remote> instead of origin to fetch the pr
" 1>&$1;
    exit $(($1 - 1));
}

OPT_BRANCH=""
OPT_REMOTE="origin"
args=0
while getopts "b:r:h" o; do
    case "${o}" in
        b) OPT_BRANCH=${OPTARG}; args=$[$args + 2] ;;
        r) OPT_REMOTE=${OPTARG}; args=$[$args + 2] ;;
        h) usage 1;;
        \?) usage 2;;
    esac
done
shift $args

if [ $# -ne 1 ]; then
    usage 2
fi

PR=$1

if [ -n "$OPT_BRANCH" ] && [ $(git rev-parse $OPT_BRANCH) ]; then
    echo "Branch $OPT_BRANCH already exists" >&2
    exit 1
fi

git fetch $OPT_REMOTE refs/pull/$PR/head:$OPT_BRANCH
