#!/bin/bash

function die() {
    echo "ERROR: $*" >&2
    exit 1
}

(( EUID == 0 )) || echo 'This script must be run with root privileges' >&2

set -ex

DEVICE="/dev/sda"
ROOT_PART="2"

sync
echo 3 > /proc/sys/vm/drop_caches
umount / 2>/dev/null || true
umount /home 2>/dev/null || true

exec qemu-system-x86_64 \
    -enable-kvm -smp 2 -m 512 \
    -serial stdio \
    -kernel /boot/vmlinuz-linux \
    -initrd /boot/initramfs-linux-fallback.img \
    -append "root=/dev/sda2 console=tty0 console=ttyS0 rw systemd.unit=multi-user.target" \
    -display none \
    -snapshot /dev/sda
