#!/bin/sh

if [ -z "$KVM_THAT_BIOS" ]; then
    KVM_THAT_BIOS=/usr/share/ovmf/x64/ovmf_x64.bin
    if [ ! -f $KVM_THAT_BIOS ]; then
        KVM_THAT_BIOS=/usr/share/ovmf/ovmf_x64.bin
        if [ ! -f $KVM_THAT_BIOS ]; then
            echo -e "No UEFI bios found - ovmf needs to be installed, or export KVM_THAT_BIOS pointing to it" >&2
            exit 1
        fi
    fi
fi

exec qemu-system-x86_64 \
     -serial stdio \
     -display none \
     -machine accel=kvm \
     -m 256 \
     -bios $KVM_THAT_BIOS \
     -net user,hostfwd=tcp::10022-:22,hostfwd=tcp::12345-:12345 \
     -net nic \
     $@
