#!/bin/bash

# run this script on the target disk after dd'ing the image there
# it only works when the root partition is the last one

set -e

disk=$1
ROOT_PARTITION_X86_64="F68BCE3-E8CD-4DB1-96E7-FBCAF984B709"

# Make sure we print an error message, loud and clear
trap '
    ret=$?
    set +e
    if [ $ret -ne 0 ]; then
        echo "Failed to expand root" > /dev/stderr
    fi
    ' EXIT
trap 'exit 1;' SIGINT

# Recreate partition table by removing the "last-lba" setting and the root
# partition size argument. This allows us to later extend the filesystem
# using the free space and also allows us to put the alternate GPT table to
# end of the device, where it belongs
function recreate_partition_table() {
    ptable=$(mktemp --tmpdir expand-root.XXXXXX)

    # save current GPT description
    sfdisk --dump $disk | \
        sed -e "/$ROOT_PARTITION_X86_64/s/[[:space:]]*size=[[:space:]]*[^,]*,//" \
            -e "/^last-lba/d" > $ptable

    # Erase any partition table, including MBR that might contain old partitions
    wipefs --all $disk

    # write back partition table
    sfdisk $disk < $ptable

    rm -f $ptable
}

function expand_root() {
    # now figure out what is the root parition and extend it
    read part xxxxx <<<$(sfdisk --dump $disk | grep $ROOT_PARTITION_X86_64)
    e2fsck -f $part
    resize2fs $part
}

recreate_partition_table
expand_root
