#!/bin/bash

# run this script on the target disk after dd'ing the image there
# it only works when the root partition is the last one

set -e

disk=$1

# Make sure we print an error message, loud and clear
trap '
    ret=$?
    set +e
    if [ $ret -ne 0 ]; then
        echo "Failed to expand root" > /dev/stderr
    fi
    ' EXIT
trap 'exit 1;' SIGINT

# Recreate partition table by removing the "last-lba" setting and the root
# partition size argument. This allows us to later extend the filesystem
# using the free space and also allows us to put the alternate GPT table to
# end of the device, where it belongs
function recreate_partition_table() {
    ptable=$(mktemp --tmpdir expand-part.XXXXXX)

    # save current GPT description
    sfdisk --dump $disk | \
        sed -e "/$1/s/[[:space:]]*size=[[:space:]]*[^,]*,//" \
            -e "/^last-lba/d" > $ptable

    # Erase any partition table, including MBR that might contain old partitions
    wipefs --all $disk

    # write back partition table
    sfdisk $disk < $ptable

    cat $ptable
    rm -f $ptable
}

function expand_last() {
    # now figure out what is the root parition and extend it
    read part xxxxx <<<$(sfdisk --dump $disk | tail -n 1)
    e2fsck -f $part
    resize2fs $part
}

last_part_uuid=$(sfdisk --dump  ~/ubuntu-19.10.raw | tail -n 1 | sed 's/.*uuid=\([^ ,]*\).*/\1/')
recreate_partition_table $last_part_uuid

F=""
if [ -f $disk ]; then
	F=$disk
	disk=$(losetup -f --show -P $F)
fi

expand_last $disk

if [ -n "$F" ]; then
	sudo losetup -d $disk
fi
