#!/bin/bash

set -eu

DRY=

rm_kernel() {
	# safer than rm -r
	$DRY find /boot -maxdepth 1 -name "*${1}*" -delete
	$DRY find /boot -maxdepth 1 -xtype l -delete
}

rm_modules() {
	$DRY find /lib/modules -maxdepth 1 -name "*${1}*" -exec rm -r {} \;
}

for k in "$@"; do
	k=${k//vmlinuz-}
	rm_kernel "$k"
	rm_modules "$k"
done

update-grub
