#!/bin/bash

# This hook configures sshd to allow root access through ssh with no password

[[ ! -f "$ROOTFS/etc/ssh/sshd_config" ]] && exit 1

cat <<EOF >> "$ROOTFS/etc/ssh/sshd_config"

# arch-installer: Allow passwordless root access.
PermitRootLogin yes
PermitEmptyPasswords yes
EOF
